language: python

python:
    - "3.4"

sudo: false

env:
    matrix:
        - TARGET=unit
        - TARGET=server_ldap
        - TARGET=server_public_api
        - TARGET=e2e_chrome
    global:
        - SCREENSHOT_DIR=/tmp/screenshots

services:
    - mongodb
    - elasticsearch
    - redis-server

cache:
  directories:
  - $HOME/.cache/pip
  - $HOME/.npm
  - $HOME/.cache/bower

before_install:
    - npm install -g grunt-cli bower ;
    - if [ "${TARGET}" != "${TARGET/e2e/}" ]; then
        export DISPLAY=:99.0 &&
        /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1920x1080x24 ;
        curl -Lo chrome.zip https://download-chromium.appspot.com/dl/Linux_x64 && unzip chrome.zip &&
        export CHROME_BIN=`pwd`/chrome-linux/chrome &&
        $CHROME_BIN --version ;
      fi

install:
    - cd server && pip install -r requirements.txt && cd ..
    - cd client && npm install && bower install && cd ..
    - cd server && pip install coveralls==1.0a2 && cd ..

before_script:
    - if [ "${TARGET}" != "${TARGET/e2e/}" ]; then
        cd server ;
        (nohup env SUPERDESK_URL='http://127.0.0.1:5000/api' SUPERDESK_CLIENT_URL='http://127.0.0.1:9000' SUPERDESK_TESTING='True' honcho start & );
        cd ../client ;
        grunt build --server='http://127.0.0.1:5000/api' --ws='ws://127.0.0.1:5100' ;
        cd dist ;
        while [ ! -f index.html ]; do sleep .5; done ;
        (nohup python3 -m http.server 9000 & );
        cd ../.. ;
      fi

script:
    - if [ "${TARGET}" = "unit" ]; then
        cd client && npm test && cd .. ;
        cd server && flake8 && cd .. ;
        cd server && behave ./features/ --format progress2 --logging-level ERROR && cd .. ;
        cd server && nosetests --with-coverage --cover-package=superdesk,apps && cd .. ;
      fi
    - if [ "${TARGET}" = "server_ldap" ]; then
        cd server &&
        LDAP_SERVER="ldap://sourcefabric.org" LDAP_BASE_FILTER="OU=Superdesk Users,dc=sourcefabric,dc=org" behave ./features/ --format progress2 --logging-level ERROR &&
        cd .. ;
      fi
    - if [ "${TARGET}" = "server_public_api" ]; then
        cd server &&
        behave ./publicapi/features/ --format progress2 --logging-level ERROR &&
        cd .. ;
      fi
    - if [ "${TARGET}" != "${TARGET/e2e/}" ]; then
        cd server &&
        python3 manage.py users:create -u admin -p admin -e 'admin@example.com' --admin=true 2>&1 ;
        cd ../client &&
        ./node_modules/.bin/webdriver-manager update &&
        ./node_modules/.bin/protractor protractor-conf.js
          --stackTrace --verbose
          --baseUrl 'http://127.0.0.1:9000'
          --params.baseBackendUrl 'http://127.0.0.1:5000/api'
          --params.username 'admin'
          --params.password 'admin'
          --capabilities.browserName "${TARGET/e2e_/}"
        ;
      fi

after_script:
    - killall -9 python

after_failure:
    - $TRAVIS_BUILD_DIR/scripts/upload_screenshots.sh

after_success:
    - if [ "${TARGET}" = "unit" ]; then
        cd client && grunt coveralls && cd .. ;
        cd server && coveralls --merge="../client/coveralls.json" ;
      fi
